# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dataid.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_DataId(object):
    def setupUi(self, DataId):
        DataId.setObjectName("DataId")
        DataId.resize(377, 365)
        self.centralwidget = QtWidgets.QWidget(DataId)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        DataId.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DataId)
        self.statusbar.setObjectName("statusbar")
        DataId.setStatusBar(self.statusbar)

        self.retranslateUi(DataId)
        QtCore.QMetaObject.connectSlotsByName(DataId)

    def retranslateUi(self, DataId):
        _translate = QtCore.QCoreApplication.translate
        DataId.setWindowTitle(_translate("DataId", "DataId"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DataId", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DataId", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DataId", "Email"))

        conn=sqlite3.connect("FacaBase.db")
        cmd = "SELECT * FROM People"
        cursor=conn.execute(cmd)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(cursor):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()
        
