# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_deadline.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
import sqlite3
import time, threading

import datetime
import smtplib


class Ui_Deadline(object):
    def setupUi(self, Deadline):
        Deadline.setObjectName("MainWindow")
        Deadline.resize(580, 509)
        self.centralwidget = QtWidgets.QWidget(Deadline)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 561, 411))
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Deadline.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Deadline)
        self.statusbar.setObjectName("statusbar")
        Deadline.setStatusBar(self.statusbar)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 460, 381, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 460, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 460, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.kirimemail)
        self.retranslateUi(Deadline)
        QtCore.QMetaObject.connectSlotsByName(Deadline)

    def kirimemail(self):
        gmailaddress = ("face.perpus@gmail.com")
        gmailpassword = ("faceperpus123")
        mailto = self.lineEdit.text()
        msg = ("Hallo!! Sekedar mengingatkan bahwa pengembalian buku tinggal 1 hari lagi!!")
        #Isikan msg dengan isi email yang diinginkan
        mailserver = smtplib.SMTP('smtp.gmail.com',587)
        mailserver.starttls()
        mailserver.login(gmailaddress, gmailpassword)
        mailserver.sendmail(gmailaddress, mailto, msg)
        print("sent!")
        mailserver.quit()
        msgBox = QMessageBox()
        msgBox.setWindowTitle("Send Email")
        msgBox.setText("Email berhasil terkirim")
        x = msgBox.exec_()

    def retranslateUi(self, Deadline):
        _translate = QtCore.QCoreApplication.translate
        Deadline.setWindowTitle(_translate("MainWindow", "Deadline"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Buku"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pengambalian"))
        self.label.setText(_translate("MainWindow", "Deadline 1 hari pengembalian"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.pushButton.setText(_translate("MainWindow", "Kirim Email"))

        DateTime = datetime.datetime.now()
        dt = ('%s%s%s' % ((DateTime.day), DateTime.month, DateTime.year))
        #Baris diatas hanya sebagai contoh simulasi
        #Jika ingin memberikan durasi deadline pada peminjaman silahkan ganti dengan
        #  DateTime.day-x    x = 1 untuk satu hari dan seterusnya
        conn=sqlite3.connect("database/Harian/"+str(dt)+".db")
        cmd = "SELECT * FROM Pinjaman"
        cursor=conn.execute(cmd)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(cursor):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()



