# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tambahbuku.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
import pickle
import sqlite3
import serial
import time, threading

global ser
ser = serial.Serial('COM6',baudrate=9600, timeout=10,
                    parity=serial.PARITY_NONE,
                    stopbits=serial.STOPBITS_ONE,
                    bytesize=serial.EIGHTBITS
                    )


class Ui_Tambahbuku(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 100, 301, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 130, 301, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 160, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.simpan)

        
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 70, 301, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 160, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.bukadata)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 421, 301))
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TAMBAH BUKU"))
        self.label.setText(_translate("MainWindow", "Tambah Buku:"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "NAMA BUKU"))
        self.label_4.setText(_translate("MainWindow", "JENIS BUKU"))
        self.pushButton.setText(_translate("MainWindow", "SIMPAN"))
        self.label_5.setText(_translate("MainWindow", "KODE BUKU"))
        self.label_7.setText(_translate("MainWindow", "Scan RFID Terlebih dulu"))
        self.pushButton_2.setText(_translate("MainWindow", "Data Buku"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pinjam"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kembali"))
        self.timeout = 0
        self.check_serial_event()

    def check_serial_event(self):
        self.timeout += 1
        serial_thread = threading.Timer(1, self.check_serial_event)
        if ser.is_open == True:
            serial_thread.start()
            if ser.in_waiting:
                eol = b'\n'
                leneol = len(eol)
                line = bytearray()
                while True:
                    c = ser.read(1)
                    if c:
                        line += c
                        if line[-leneol:] == eol:
                            break
                    else:
                        break
                line = line.rstrip()
                distance = line.decode("utf-8")
                self.lineEdit_4.setText(distance)
                self.timeout = 0
        if self.timeout >= 100:
            ser.close()

    def bukadata(self):
        conn=sqlite3.connect("database/Buku/"+self.lineEdit_4.text()+".db")
        cmd = "SELECT * FROM BUKU"
        cursor=conn.execute(cmd)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(cursor):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()
        

    def simpan(self):
        def insertData(Id, Kode, Nama, Jenis):
            conn = sqlite3.connect("FacaBase.db")
            cmd = "SELECT * FROM Buku WHERE ID="+str(Id)
            cursor = conn.execute(cmd)
            isRecordExist=0
            for row in cursor:
                isRecordExist=1
            if(isRecordExist==1):
                cmd = "UPDATE Buku SET Kode="+str(Kode)+"WHERE ID="+str(Id)
                cmd = "UPDATE Buku SET Nama="+str(Nama)+"WHERE ID="+str(Id)
                cmd = "UPDATE Buku SET Jenis="+str(Jenis)+"WHERE ID="+str(Id)
            else:
                cmd="INSERT INTO Buku(ID,Kode,Nama,Jenis) Values("+str(Id)+","+str(Kode)+","+str(Nama)+","+str(Jenis)+")"
            conn.execute(cmd)
            conn.commit()
            conn.close()
        def makeData(kode):
            conn = sqlite3.connect("database/Buku/"+kode+".db")
            conn.close()
            print("Berhasil membuat database buku")
        def makeTabel(kode):
            conn = sqlite3.connect('database/Buku/'+kode+'.db')
            cursor =conn.cursor()
            sql = '''CREATE TABLE BUKU(ID INT, Nama CHAR(20), Pinjam INT, Kembali INT)'''
            cursor.execute(sql)
            conn.commit()
            conn.close()
            
        id = self.lineEdit.text()
        kode = self.lineEdit_4.text()
        nama = "'"+self.lineEdit_2.text()+"'"
        jenis = "'"+self.lineEdit_3.text()+"'"

        insertData(id, kode, nama, jenis)
        makeData(kode)
        makeTabel(kode)
            
        self.lineEdit_4.setText("")
        self.lineEdit_3.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit.setText("")

        msgBox = QMessageBox()
        msgBox.setWindowTitle("Tambah Buku")
        msgBox.setText("Buku berhasil ditambahkan")
        x = msgBox.exec_()

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Tambahbuku()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())





    
            
    
