# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
import serial
import time, threading
from ui_main_window import *
from takephoto import Ui_MainWindow
from pinjaman import Ui_Pinjaman
from dataid import Ui_DataId
from deadline import Ui_Deadline
import time, threading
import sqlite3

import datetime


class Ui_Form(object):

    def openTakePhoto(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPinjaman(self):
        self.window = QtWidgets.QMainWindow()
        self.message = str(self.lineEdit_2.text())
        self.message2 = str(self.lineEdit.text())
        self.message3 = str(self.lineEdit_6.text())
        self.ui = Ui_Pinjaman(self.message,self.message2,self.message3)
        self.ui.setupUi(self.window)
        self.window.show()

    def openDataID(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DataId()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDeadline(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Deadline()
        self.ui.setupUi(self.window)
        self.window.show()

    def deleteData(self):
        id = self.lineEdit_2.text()
        conn=sqlite3.connect("database/"+str(id)+".db")
        cursor = conn.cursor()
        row = self.lineEdit_3.text()
        entry = (row,)
        cursor.execute('DELETE FROM BUKU WHERE rowid= ?;',entry)
        conn.commit()
        conn.close()
        self.lineEdit_3.setText("")
        msgBox = QMessageBox()
        msgBox.setWindowTitle("Pengembalian")
        msgBox.setText("Buku sudah dikembalikan!!")
        x = msgBox.exec_()
       

        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(982, 551)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 621, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(self.layoutWidget)
        self.image_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.image_label)
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setGeometry(QtCore.QRect(10, 480, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt.setFont(font)
        self.control_bt.setAutoDefault(False)
        self.control_bt.setObjectName("control_bt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(650, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(650, 50, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(740, 80, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(650, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(740, 50, 221, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.control_bt_2 = QtWidgets.QPushButton(Form)
        self.control_bt_2.setGeometry(QtCore.QRect(810, 480, 151, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt_2.setFont(font)
        self.control_bt_2.setAutoDefault(False)
        self.control_bt_2.setObjectName("control_bt_2")
        self.control_bt_2.clicked.connect(self.openPinjaman)
        
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 130, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(650, 160, 311, 291))
        self.tableView.setObjectName("tableView")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(810, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.control_bt_3 = QtWidgets.QPushButton(Form)
        self.control_bt_3.setGeometry(QtCore.QRect(190, 480, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt_3.setFont(font)
        self.control_bt_3.setAutoDefault(False)
        self.control_bt_3.setObjectName("control_bt_3")
        self.control_bt_3.clicked.connect(self.openTakePhoto)
        self.control_bt_4 = QtWidgets.QPushButton(Form)
        self.control_bt_4.setGeometry(QtCore.QRect(370, 480, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt_4.setFont(font)
        self.control_bt_4.setAutoDefault(False)
        self.control_bt_4.setObjectName("control_bt_4")
        self.control_bt_4.clicked.connect(self.openDataID)
        
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(650, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(740, 110, 221, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.control_bt_5 = QtWidgets.QPushButton(Form)
        self.control_bt_5.setGeometry(QtCore.QRect(550, 480, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt_5.setFont(font)
        self.control_bt_5.setAutoDefault(False)
        self.control_bt_5.setObjectName("control_bt_5")
        self.control_bt_5.clicked.connect(self.openDeadline)
        
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 519, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(650, 170, 311, 281))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.control_bt_6 = QtWidgets.QPushButton(Form)
        self.control_bt_6.setGeometry(QtCore.QRect(710, 480, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_bt_6.setFont(font)
        self.control_bt_6.setAutoDefault(False)
        self.control_bt_6.setObjectName("control_bt_6")
        self.control_bt_6.clicked.connect(self.deleteData)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(650, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(650, 480, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Face Recognition RFID Arduino"))
        self.image_label.setText(_translate("Form", "."))
        self.control_bt.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "Isilah data berikut :"))
        self.label_2.setText(_translate("Form", "ID"))
        self.label_3.setText(_translate("Form", "NAMA"))
        self.control_bt_2.setText(_translate("Form", "Pinjam"))
        self.label_4.setText(_translate("Form", "Daftar Pinjaman:"))
        self.label_5.setText(_translate("Form", "Tambah Pinjaman:"))
        self.control_bt_3.setText(_translate("Form", "Tambah Data Wajah"))
        self.control_bt_4.setText(_translate("Form", "Lihat Data ID"))
        self.label_9.setText(_translate("Form", "EMAIL"))
        self.control_bt_5.setText(_translate("Form", "Cek"))
        self.label_10.setText(_translate("Form", "CATATAN: Matikan/Stop kamera saat sedang tidak digunakan"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Kode"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Buku"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Pinjam"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Kembali"))
        self.control_bt_6.setText(_translate("Form", "Kembali"))
        self.label_6.setText(_translate("Form", "Masukkan No:"))


        msgBox = QMessageBox()
        msgBox.setWindowTitle("Buat database")
        msgBox.setText("Ingin membuat database peminjaman untuk hari ini?")
        msgBox.setInformativeText(" -Pilih Ok untuk membuat\n -Pilih Cancel jika sudah membuat")
        msgBox.setIcon(QMessageBox.Question)
        msgBox.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
        msgBox.setDefaultButton(QMessageBox.Cancel)
        
        x = msgBox.exec_()
        if x == QMessageBox.Ok:
            print('Yes')
            def makeData(Id):
                conn = sqlite3.connect("database/Harian/"+Id+".db")
                conn.close()
                print("Sukses Create Data")
            def makeTabel(Id):
                conn = sqlite3.connect('database/Harian/'+Id+'.db')
                cursor = conn.cursor()
                sql = '''CREATE TABLE Pinjaman(ID INT, Nama CHAR(20),Email CHAR(20),Buku CHAR(20), Pengembalian INT)'''
                cursor.execute(sql)
                conn.commit()
                conn.close()

            DateTime = datetime.datetime.now()
            dt = '%s%s%s' % (DateTime.day, DateTime.month, DateTime.year)
            print (dt)
            makeData(str(dt))
            makeTabel(str(dt))
        
